### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'encoding'

### ISSUE THREAD

**Issue by Niladri-Chakraborty** [miotto/treetagger-python#13]
Hello Sir, 
I installed all the prerequisites. But when the run the code treetagger_python2.py I got the above error, though when I go through the actual file I could see the init method does take the parameter encoding

File "treetagger_python2.py", line 47, in __main__.TreeTagger
Failed example:
    tt = TreeTagger(encoding='utf-8',language='english')
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/doctest.py", line 1315, in __run
        compileflags, 1) in test.globs
      File "<doctest __main__.TreeTagger[1]>", line 1, in <module>
        tt = TreeTagger(encoding='utf-8',language='english')
TypeError: __init__() got an unexpected keyword argument 'encoding'

**Comment by poornagurram** [comment]
you might be running in Python 3.I got the same error and removed the argument and the error was gone.

**Comment by tgrrr** [comment]
pip3 install -U html5lib=="0.9999999"

here's the [html5lib bug on github][1] 

  [1]: https://github.com/html5lib/html5lib-python/issues/281

from: https://stackoverflow.com/a/39087283

**Comment by miotto** [comment]
Python 2 is no longer supported, please use Python 3.
