### ISSUE TITLE
Throws out a a LookupError

### ISSUE THREAD

**Issue by roybayot** [miotto/treetagger-python#8]
Hi. I need some help. I was able to run it before. But I dont know why it doesnt work anymore. It prints this error below. I've edited the .bash_profile and .zshrc also. I'm sorry also, I dont know if I should ask it here.

LookupError: 

===========================================================================
NLTK was unable to find the tree-tagger-english file!
Use software specific configuration paramaters or set the TREETAGGER environment variable.

  Searched in:
    - .
    - /usr/bin
    - /usr/local/bin
    - /opt/local/bin
    - /Applications/bin
    - /Users/roybayot/bin
    - /Users/roybayot/Applications/bin
    - /Users/roybayot/work/TreeTagger/cmd

  For more information, on tree-tagger-english, see:
    <http://www.cis.uni-muenchen.de/~schmid/tools/TreeTagger/>
===========================================================================

# Added to my .zshrc the things written below. My .bash_profile is also similar. 

# Configure TREE TAGGER PATH                                                                                                                                                    
export TREE_TAGGER_PATH='/Users/roybayot/Desktop/new_tree_tagger/'               
export TREE_TAGGER_PATH=$TREE_TAGGER_PATH:/Users/roybayot/Desktop/new_tree_tagger
export TREE_TAGGER_PATH=$TREE_TAGGER_PATH:/Users/roybayot/Desktop/new_tree_tagger/bin
export TREE_TAGGER_PATH=$TREE_TAGGER_PATH:/Users/roybayot/Desktop/new_tree_tagger/cmd
                                                                                  
export TREETAGGER_HOME='/Users/roybayot/Desktop/new_tree_tagger/'                
export TREETAGGER_HOME=$TREETAGGER_HOME:/Users/roybayot/Desktop/new_tree_tagger  
export TREETAGGER_HOME=$TREETAGGER_HOME:/Users/roybayot/Desktop/new_tree_tagger/bin
export TREETAGGER_HOME=$TREETAGGER_HOME:/Users/roybayot/Desktop/new_tree_tagger/cmd
                                                                                 
export TREETAGGER='/Users/roybayot/Desktop/new_tree_tagger/'                     
export TREETAGGER=$TREETAGGER:/Users/roybayot/Desktop/new_tree_tagger            
export TREETAGGER=$TREETAGGER:/Users/roybayot/Desktop/new_tree_tagger/bin        
export TREETAGGER=$TREETAGGER:/Users/roybayot/Desktop/new_tree_tagger/cmd        
export TAGDIR=/Users/roybayot/Desktop/new_tree_tagger/                           
                                                                                                                                                                    export TREETAGGER_HOME=/Users/roybayot/Desktop/new_tree_tagger                   
export TREETAGGER_HOME=$TREETAGGER_HOME:/Users/roybayot/Desktop/new_tree_tagger/cmd
export TREETAGGER_HOME=$TREETAGGER_HOME:/Users/roybayot/Desktop/new_tree_tagger/bin
                                                                                  
export TREE_TAGGER_PATH=/Users/roybayot/Desktop/new_tree_tagger                  
export TREE_TAGGER_PATH=$TREE_TAGGER_PATH:/Users/roybayot/Desktop/new_tree_tagger/cmd
export TREE_TAGGER_PATH=$TREE_TAGGER_PATH:/Users/roybayot/Desktop/new_tree_tagger/bin
                                                                                  
export TREETAGGER_HOME=/Users/roybayot/Desktop/new_tree_tagger                   
export TREETAGGER_HOME=$TREETAGGER_HOME:/Users/roybayot/Desktop/new_tree_tagger/cmd
export TREETAGGER_HOME=$TREETAGGER_HOME:/Users/roybayot/Desktop/new_tree_tagger/bin

# Add python path                                                                
export PYTHONPATH=$PYTHONPATH:/Users/roybayot/Desktop/new_tree_tagger/           
export PYTHONPATH=$PYTHONPATH:/Users/roybayot/Desktop/new_tree_tagger/cmd/       
export PYTHONPATH=$PYTHONPATH:/Users/roybayot/Desktop/new_tree_tagger/bin/       
                                                                                  
# Explicitly configured $PATH variable                                           
PATH=/usr/local/git/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/opt/local/bin:/opt/local/sbin:/usr/X11/bin:/Users/roybayot/Desktop/TreeTagger:/Users/roybayot/Desktop/TreeTagger/cmd:/Users/roybayot/Desktop/TreeTagger/bin:/Users/roybayot/Desktop/new_tree_tagger:/Users/roybayot/Desktop/new_tree_tagger/cmd:/Users/roybayot/Desktop/new_tree_tagger/bin

**Comment by miotto** [comment]
Please take a look at the latest version 8397879c68ef8f72dd335405de976704211eadd6, eventually it should work again. There is also a version for Python 3 available - treetagger3.py .

**Comment by valerioorfano** [comment]
Hi, were you able to fiux the issue. I have the same issue on windows platform, cannot figure out where is the issue. Any help is appreciated.

My searched in is empty


LookupError: 

===========================================================================
NLTK was unable to find the tree-tagger-english file!
Use software specific configuration paramaters or set the TREETAGGER environment variable.

  Searched in:

  For more information on tree-tagger-english, see:
    <http://www.cis.uni-muenchen.de/~schmid/tools/TreeTagger/>
===========================================================================

**Comment by roybayot** [comment]
Hi. I just updated for the later version and it worked.

**Comment by miotto** [comment]
Thanks you for the response.
